# Support the author by using the funding link below
# Developed and maintained by Christian Coduri with the help of awesome contributors.

# Buy Me a Coffee: https://buymeacoffee.com/coduri
buy_me_a_coffee: coduri

# Your support means a lot to me to continue the development of open source project like this.